version: '3.7'

services:
  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis
    env_file:
      - .env

  api:
    container_name: ${PROJECT_NAME}_api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
     - "31337:31337"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - './api/:/usr/app'
      - './resources:/resources'
    links:
      - redis

volumes:
  redis-data:
